# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageCdrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vmname', models.CharField(max_length=100)),
                ('vcenter', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[(b'mount', b'mount'), (b'umount', b'umount')], max_length=25)),
                ('iso_path', models.CharField(blank=True, help_text='[datastore] path/to/iso', max_length=200)),
                ('returncode', models.IntegerField(default=999, help_text='No need to edit')),
                ('status', models.CharField(default='pending', help_text='No need to edit', max_length=20)),
                ('stdout', models.TextField(default='', help_text='No need to edit', max_length=100)),
                ('stderr', models.TextField(default='', help_text='No need to edit', max_length=100)),
            ],
            options={
                'ordering': ['vmname'],
            },
        ),
    ]
