unset PIP_PROXY
unset APPLICATION_DOMAIN

unset DEBUG
unset VSPHERE_USERNAME
unset VSPHERE_PASSWORD
unset PVMOMI_TIMEOUT
unset ITERATIONS_WAITING_FOR_BLOCKING_QUESTION

export PIP_PROXY='ip:port'
export APPLICATION_DOMAIN='fqdn'

export DEBUG=off
export VSPHERE_USERNAME='someusername'
export VSPHERE_PASSWORD='somepassword'
export PVMOMI_TIMEOUT=240
export ITERATIONS_WAITING_FOR_BLOCKING_QUESTION=3

# vim: ai et ts=4 sw=4 sts=4 nu ru
